"use server";

import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requirePermission, requireStaff } from "@/lib/auth";
import { blankToNull } from "@/lib/format";
import { PAYMENT_SELECT, loadInvoice, nextDocumentNumber, toPayment } from "@/lib/invoice-data";
import { newToken } from "@/lib/media";
import { round2 } from "@/lib/money";
import { notifyRoles, notifyStaff } from "@/lib/notifications";
import { decideOverpayment, recordPaymentCore, settleJob, verifyPayment, voidPayment, type Actor } from "@/lib/payments";
import { can, type RoleId } from "@/lib/roles";
import { getSettings } from "@/lib/settings";
import { convertProformaIfPaid, ensureProforma } from "@/lib/invoice-flow";
import { createAdminClient } from "@/lib/supabase/admin";

function refresh(jobId: string | null, invoiceId?: string) {
  revalidatePath("/invoices");
  if (invoiceId) revalidatePath(`/invoices/${invoiceId}`);
  if (jobId) {
    revalidatePath(`/jobs/${jobId}`);
    revalidatePath(`/jobs/${jobId}/invoice`);
    revalidatePath(`/jobs/${jobId}/gate-out`);
  }
  revalidatePath("/dashboard");
  revalidatePath("/profit");
}

async function advisorsOf(jobId: string) {
  const admin = createAdminClient();
  const [{ data: job }, { data: appr }] = await Promise.all([admin.from("jobs").select("gated_in_by").eq("id", jobId).maybeSingle(), admin.from("approval_requests").select("sent_by").eq("job_id", jobId)]);
  return Array.from(new Set([job?.gated_in_by, ...(appr ?? []).map((a) => a.sent_by)].filter((x): x is string => !!x)));
}
const actorOf = (s: { id: string; display_name: string; role_id: string; is_head_accountant?: boolean }): Actor => ({ id: s.id, display_name: s.display_name, role_id: s.role_id, is_head_accountant: s.is_head_accountant });

/** The advisor marks the car ready to invoice; accounts are told. */
export async function markReadyToInvoice(jobId: string) {
  const staff = await requirePermission("markReadyToInvoice");
  const admin = createAdminClient();
  const { data: job } = await admin.from("jobs").select("id, job_number, status, is_open, ready_to_invoice_at").eq("id", jobId).maybeSingle();
  if (!job || !job.is_open) redirect(`/jobs/${jobId}?error=${encodeURIComponent("This job is closed.")}`);
  if (!["ready", "pending_wash", "pending_qc", "pending_payment"].includes(job.status)) redirect(`/jobs/${jobId}?error=${encodeURIComponent("The car is not ready yet.")}`);
  const settings = await getSettings();
  await admin.from("jobs").update({ ready_to_invoice_at: new Date().toISOString(), ready_to_invoice_by: staff.id }).eq("id", jobId);
  const inv = await ensureProforma(jobId, { id: staff.id, display_name: staff.display_name }, settings);
  refresh(jobId);
  if (!inv) redirect(`/jobs/${jobId}?error=${encodeURIComponent("Nothing to invoice: no approved quotation and no inspection fee.")}`);
  redirect(`/jobs/${jobId}?message=${encodeURIComponent(inv!.kind === "proforma" ? `${inv!.number} is ready. Send it to the customer.` : `${inv!.number} is the tax invoice for this job.`)}`);
}

/**
 * The tax invoice is generated by itself when the proforma is paid in full. This screen's button
 * prepares a missing proforma; only the owner can issue the tax invoice while money is still owed,
 * with a reason that accounts are told.
 */
export async function issueInvoice(jobId: string, formData: FormData) {
  const staff = await requirePermission("issueInvoices");
  const back = `/jobs/${jobId}/invoice`;
  const admin = createAdminClient();
  const settings = await getSettings();
  const reason = blankToNull(formData.get("reason"));
  const { data: job } = await admin.from("jobs").select("id, job_number, status, is_open").eq("id", jobId).maybeSingle();
  if (!job || !job.is_open) redirect(`${back}?error=${encodeURIComponent("This job is closed.")}`);
  const { data: existing } = await admin.from("invoices").select("id, number").eq("job_id", jobId).eq("kind", "tax_invoice").eq("status", "issued").eq("is_active", true).maybeSingle();
  if (existing) redirect(`/invoices/${existing.id}?error=${encodeURIComponent(`${existing.number} is already issued for this job. Corrections are by credit note.`)}`);
  const { data: before } = await admin.from("invoices").select("id").eq("job_id", jobId).eq("kind", "proforma").eq("status", "issued").eq("is_active", true).is("converted_to", null).limit(1);
  const hadProforma = (before ?? []).length > 0;
  const inv = await ensureProforma(jobId, { id: staff.id, display_name: staff.display_name }, settings);
  if (!inv) redirect(`${back}?error=${encodeURIComponent("Nothing to invoice: no approved quotation and no inspection fee.")}`);
  refresh(jobId, inv!.id);
  if (inv!.kind === "tax_invoice") redirect(`/invoices/${inv!.id}?message=${encodeURIComponent(`${inv!.number} issued: paid in full.`)}`);
  if (!hadProforma) redirect(`${back}?message=${encodeURIComponent(`${inv!.number} prepared. The advisor sends it; the tax invoice follows when it is paid in full.`)}`);
  if (staff.role_id !== "owner") redirect(`${back}?error=${encodeURIComponent("The tax invoice is generated by itself when the proforma is paid in full. Only the owner can issue it earlier, with a reason.")}`);
  if (!reason || reason.length < 3) redirect(`${back}?error=${encodeURIComponent("Write the reason for issuing the tax invoice before full payment; accounts are told.")}`);
  const tax = await convertProformaIfPaid(jobId, staff.id, settings, { force: { reason } });
  if (!tax) redirect(`${back}?error=${encodeURIComponent("Could not issue the tax invoice.")}`);
  refresh(jobId, tax!.id);
  redirect(`/invoices/${tax!.id}?message=${encodeURIComponent(`${tax!.number} issued before full payment. Accounts have been told.`)}`);
}

/**
 * A payment: cash, card, link or cheque, against an invoice or as a deposit on the job. One tap, one
 * receipt: the same tap twice records nothing twice; more than the balance waits for the owner.
 */
export async function recordPayment(formData: FormData) {
  const staff = await requirePermission("recordPayments");
  const settings = await getSettings();
  const invoiceId = blankToNull(formData.get("invoice_id"));
  const jobIdIn = blankToNull(formData.get("job_id"));
  const returnTo = blankToNull(formData.get("return_to"));
  const base = invoiceId ? `/invoices/${invoiceId}` : jobIdIn ? `/jobs/${jobIdIn}/invoice` : "/invoices";
  const back = returnTo && returnTo.startsWith(base) && !returnTo.includes("message=") && !returnTo.includes("error=") ? returnTo : base;
  const sep = back.includes("?") ? "&" : "?";
  const amount = Number(String(formData.get("amount") ?? "").replace(/[^\d.]/g, ""));
  const r = await recordPaymentCore(actorOf(staff), {
    invoiceId,
    jobId: jobIdIn,
    method: String(formData.get("method") ?? ""),
    amount,
    reference: blankToNull(formData.get("reference")),
    cheque: { number: blankToNull(formData.get("cheque_number")), bank: blankToNull(formData.get("cheque_bank")), date: blankToNull(formData.get("cheque_date")) },
    notes: blankToNull(formData.get("notes")),
    clientKey: blankToNull(formData.get("client_key")),
  }, settings);
  const jobId = jobIdIn ?? (invoiceId ? (await loadInvoice(invoiceId))?.invoice.job_id ?? null : null);
  refresh(jobId, invoiceId ?? undefined);
  redirect(`${back}${sep}${r.error ? "error" : "message"}=${encodeURIComponent(r.error ?? r.message ?? "Recorded.")}`);
}

/** A wrong receipt is never deleted: the owner or the head accountant voids it with a reason. */
export async function voidPaymentAction(paymentId: string, formData: FormData) {
  const staff = await requireStaff();
  const r = await voidPayment(paymentId, actorOf(staff), String(formData.get("reason") ?? ""));
  const { data: p } = await createAdminClient().from("payments").select("job_id, invoice_id").eq("id", paymentId).maybeSingle();
  refresh(p?.job_id ?? null, p?.invoice_id ?? undefined);
  const back = p?.invoice_id ? `/invoices/${p.invoice_id}` : "/invoices";
  redirect(`${back}?${r.error ? "error" : "message"}=${encodeURIComponent(r.error ?? r.message ?? "Voided.")}`);
}

/** Accounts tick a payment once the money is confirmed. */
export async function verifyPaymentAction(paymentId: string, formData: FormData) {
  const staff = await requirePermission("verifyPayments");
  const r = await verifyPayment(paymentId, actorOf(staff));
  const { data: p } = await createAdminClient().from("payments").select("job_id, invoice_id").eq("id", paymentId).maybeSingle();
  refresh(p?.job_id ?? null, p?.invoice_id ?? undefined);
  const to = blankToNull(formData.get("return_to")) ?? (p?.invoice_id ? `/invoices/${p.invoice_id}` : "/invoices");
  redirect(`${to}${to.includes("?") ? "&" : "?"}${r.error ? "error" : "message"}=${encodeURIComponent(r.error ?? r.message ?? "Verified.")}`);
}

/** The owner approves or refuses a payment above the balance. */
export async function decideOverpaymentAction(paymentId: string, formData: FormData) {
  const staff = await requirePermission("moveJobs");
  const approve = String(formData.get("decision") ?? "") === "approve";
  const r = await decideOverpayment(paymentId, actorOf(staff), approve, blankToNull(formData.get("note")));
  const { data: p } = await createAdminClient().from("payments").select("job_id, invoice_id").eq("id", paymentId).maybeSingle();
  refresh(p?.job_id ?? null, p?.invoice_id ?? undefined);
  const back = p?.invoice_id ? `/invoices/${p.invoice_id}` : "/invoices";
  redirect(`${back}?${r.error ? "error" : "message"}=${encodeURIComponent(r.error ?? r.message ?? "Done.")}`);
}

/** The owner or accounts paste the bank's payment link; the customer's invoice page shows "Pay now". */
export async function setPaymentLink(invoiceId: string, formData: FormData) {
  const staff = await requireStaff();
  const role = staff.role_id as RoleId;
  if (!can(role, "issueInvoices")) redirect(`/invoices/${invoiceId}`);
  const url = blankToNull(formData.get("payment_link_url"));
  if (url && !/^https:\/\/\S+$/.test(url)) redirect(`/invoices/${invoiceId}?error=${encodeURIComponent("Paste the full https:// link.")}`);
  const admin = createAdminClient();
  await admin.from("invoices").update({ payment_link_url: url, updated_by: staff.id }).eq("id", invoiceId);
  const { data: inv } = await admin.from("invoices").select("job_id, number").eq("id", invoiceId).maybeSingle();
  if (inv?.job_id) await admin.from("job_events").insert({ job_id: inv.job_id, event_type: "payment_link", note: url ? `Payment link added to ${inv.number} by ${staff.display_name}` : `Payment link removed from ${inv.number} by ${staff.display_name}`, created_by: staff.id });
  refresh(inv?.job_id ?? null, invoiceId);
  redirect(`/invoices/${invoiceId}?message=${encodeURIComponent(url ? "Payment link saved. The customer sees Pay now on the invoice page." : "Payment link removed.")}`);
}

/** A cheque clears, or bounces (which reverses the payment). */
export async function setChequeStatus(paymentId: string, formData: FormData) {
  const staff = await requirePermission("recordPayments");
  const admin = createAdminClient();
  const { data: raw } = await admin.from("payments").select(PAYMENT_SELECT).eq("id", paymentId).maybeSingle();
  if (!raw) redirect("/invoices");
  const p = toPayment(raw as Record<string, unknown>);
  const back = p.invoice_id ? `/invoices/${p.invoice_id}` : "/invoices";
  const status = String(formData.get("status") ?? "");
  if (p.method !== "cheque" || !["cleared", "bounced"].includes(status)) redirect(back);
  const now = new Date().toISOString();
  await admin.from("payments").update(status === "cleared" ? { cheque_status: "cleared", cleared_at: now, updated_by: staff.id } : { cheque_status: "bounced", status: "reversed", reversed_at: now, reversed_reason: "Cheque bounced", updated_by: staff.id }).eq("id", paymentId);
  if (p.job_id) {
    await admin.from("job_events").insert({ job_id: p.job_id, event_type: "payment", note: `${p.number}: cheque ${p.cheque_number ?? ""} ${status} (${staff.display_name})`, created_by: staff.id });
    if (p.invoice_id) await settleJob(p.job_id, p.invoice_id, staff.id);
    if (status === "bounced") {
      const advisors = await advisorsOf(p.job_id);
      await notifyStaff(advisors, { type: "cheque_bounced", title: `Cheque bounced · ${p.number}`, body: `AED ${p.amount_aed.toLocaleString("en-GB")} reversed. The balance is due again.`, jobId: p.job_id, href: back });
      await notifyRoles(["owner"], { type: "cheque_bounced", title: `Cheque bounced · ${p.number}`, body: `AED ${p.amount_aed.toLocaleString("en-GB")} reversed.`, jobId: p.job_id, href: back });
    }
  }
  refresh(p.job_id, p.invoice_id ?? undefined);
  redirect(`${back}?message=${encodeURIComponent(status === "cleared" ? "Cheque cleared." : "Cheque bounced: the payment is reversed.")}`);
}

/** Accounts ask the owner for a credit note. */
export async function requestCreditNote(invoiceId: string, formData: FormData) {
  const staff = await requirePermission("issueInvoices");
  const reason = blankToNull(formData.get("reason"));
  const back = `/invoices/${invoiceId}`;
  if (!reason || reason.length < 3) redirect(`${back}?error=${encodeURIComponent("Say what needs correcting.")}`);
  const bundle = await loadInvoice(invoiceId);
  if (!bundle) redirect("/invoices");
  await notifyRoles(["owner"], { type: "credit_note_approval", title: `Credit note requested · ${bundle.invoice.number}`, body: `${staff.display_name}: ${reason}`, jobId: bundle.invoice.job_id, href: back });
  if (bundle.invoice.job_id) await createAdminClient().from("job_events").insert({ job_id: bundle.invoice.job_id, event_type: "credit_note_request", note: `${staff.display_name} asked the owner for a credit note on ${bundle.invoice.number}: ${reason}`, created_by: staff.id });
  redirect(`${back}?message=${encodeURIComponent("The owner has been asked to approve a credit note.")}`);
}

/** The owner issues a credit note against an invoice: an amount before VAT with a description. The invoice itself stays locked. */
export async function issueCreditNote(invoiceId: string, formData: FormData) {
  const staff = await requirePermission("approveCreditNotes");
  const back = `/invoices/${invoiceId}`;
  const bundle = await loadInvoice(invoiceId);
  if (!bundle || bundle.invoice.kind !== "tax_invoice") redirect("/invoices");
  const amount = Number(String(formData.get("amount") ?? "").replace(/[^\d.]/g, ""));
  const description = blankToNull(formData.get("description"));
  if (!Number.isFinite(amount) || amount <= 0) redirect(`${back}?error=${encodeURIComponent("Enter the amount before VAT to credit.")}`);
  if (!description) redirect(`${back}?error=${encodeURIComponent("Describe the correction.")}`);
  const credited = bundle.creditNotes.filter((c) => c.status === "issued").reduce((a, c) => a + c.taxable_aed, 0);
  if (amount + credited > bundle.invoice.taxable_aed + 0.005) redirect(`${back}?error=${encodeURIComponent("That is more than the invoice.")}`);
  const settings = await getSettings();
  const vatPct = bundle.invoice.taxable_aed ? round2((bundle.invoice.vat_aed / bundle.invoice.taxable_aed) * 100) || 5 : 5;
  const vat = round2(amount * (vatPct / 100));
  const number = await nextDocumentNumber("credit_note", settings);
  const admin = createAdminClient();
  const { data: cn, error } = await admin.from("invoices").insert({ number, kind: "credit_note", job_id: bundle.invoice.job_id, customer_id: bundle.invoice.customer_id, vehicle_id: bundle.invoice.vehicle_id, credit_of: invoiceId, token: newToken(), subtotal_aed: round2(amount), discount_aed: 0, taxable_aed: round2(amount), vat_aed: vat, total_aed: round2(amount + vat), prepared_by: staff.id, issued_by: staff.id, approved_by: staff.id, notes: `Credit against ${bundle.invoice.number}: ${description}`, customer_snapshot: bundle.invoice.customer_snapshot, vehicle_snapshot: bundle.invoice.vehicle_snapshot, created_by: staff.id, updated_by: staff.id }).select("id").single();
  if (error || !cn) redirect(`${back}?error=${encodeURIComponent(error?.message ?? "Could not issue the credit note.")}`);
  await admin.from("invoice_lines").insert({ invoice_id: cn.id, position: 0, section: "services", description, quantity: 1, unit_price: round2(amount), amount_aed: round2(amount), vat_aed: vat, total_aed: round2(amount + vat), created_by: staff.id, updated_by: staff.id });
  if (bundle.invoice.job_id) await admin.from("job_events").insert({ job_id: bundle.invoice.job_id, event_type: "credit_note", note: `${number} issued by ${staff.display_name} against ${bundle.invoice.number}: AED ${round2(amount + vat).toLocaleString("en-GB", { minimumFractionDigits: 2 })} with VAT (${description})`, created_by: staff.id });
  refresh(bundle.invoice.job_id, invoiceId);
  redirect(`/invoices/${cn.id}?message=${encodeURIComponent(`${number} issued.`)}`);
}

/** Records that the "car is ready" message with the invoice went to the customer. */
export async function markReadySent(jobId: string, method: string): Promise<{ error?: string; ok?: boolean }> {
  const staff = await requirePermission("sendApproval");
  const admin = createAdminClient();
  await admin.from("jobs").update({ ready_sent_at: new Date().toISOString() }).eq("id", jobId);
  await admin.from("job_events").insert({ job_id: jobId, event_type: "ready_sent", note: `Proforma and "your car is ready" sent by ${staff.display_name} (${method})`, created_by: staff.id });
  refresh(jobId);
  return { ok: true };
}

/** The advisor sent the tax invoice link once the proforma was paid. */
export async function markInvoiceSent(jobId: string, method: string): Promise<{ error?: string; ok?: boolean }> {
  const staff = await requirePermission("sendApproval");
  const admin = createAdminClient();
  await admin.from("jobs").update({ invoice_sent_at: new Date().toISOString() }).eq("id", jobId);
  await admin.from("job_events").insert({ job_id: jobId, event_type: "invoice_sent", note: `Tax invoice sent by ${staff.display_name} (${method})`, created_by: staff.id });
  refresh(jobId);
  return { ok: true };
}

/** Accounts or the owner change the bank charge per payment method; the quotation's hidden charge follows the highest. */
export async function updateBankCharges(formData: FormData) {
  const staff = await requirePermission("issueInvoices");
  const admin = createAdminClient();
  const keys = ["bank_charge_card_percent", "bank_charge_link_percent", "bank_charge_cash_percent", "bank_charge_cheque_percent"] as const;
  const values: Record<string, number> = {};
  for (const k of keys) {
    const n = Number(String(formData.get(k) ?? "").trim().replace(",", "."));
    if (!Number.isFinite(n) || n < 0 || n > 20) redirect(`/invoices?error=${encodeURIComponent("Each bank charge is a number between 0 and 20.")}`);
    values[k] = Math.round(n * 100) / 100;
  }
  values.bank_charge_fee_percent = Math.max(...keys.map((k) => values[k]));
  for (const [key, value] of Object.entries(values)) await admin.from("settings").update({ value }).eq("key", key);
  await admin.from("audit_log").insert({ table_name: "settings", record_id: null, action: "update", new_data: { bank_charges: values, by: staff.display_name } }).then(() => null, () => null);
  revalidatePath("/invoices");
  revalidatePath("/settings");
  redirect(`/invoices?message=${encodeURIComponent("Bank charges saved: card " + values.bank_charge_card_percent + "%, link " + values.bank_charge_link_percent + "%, cash " + values.bank_charge_cash_percent + "%, cheque " + values.bank_charge_cheque_percent + "%.")}`);
}

