import { notFound } from "next/navigation";
import { Badge, Button, Card, LinkButton, Notice, PageHeader, SectionLabel, Textarea } from "@/components/ui";
import { requirePermission } from "@/lib/auth";
import { formatDateTime } from "@/lib/format";
import { INVOICE_SELECT, PAYMENT_SELECT, buildInvoiceDraft, invoiceBalance, toInvoice, toPayment } from "@/lib/invoice-data";
import { loadJobCard, vehicleTitle } from "@/lib/job-data";
import { STATUS_LABELS } from "@/lib/jobs";
import { can, type RoleId } from "@/lib/roles";
import { getSettings } from "@/lib/settings";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { formatPlate } from "@/lib/types";
import { PaymentForm } from "@/app/(app)/invoices/[id]/PaymentForm";
import { issueInvoice, recordPayment } from "@/app/(app)/invoices/actions";

export const dynamic = "force-dynamic";

/** Money on screen: two decimals and thousands separators. */
const m = (n: number) => n.toLocaleString("en-GB", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

/**
 * The invoice is a straight copy of the approved quotation: the same lines, the same discount, the same
 * rounded total. Accounts press "Issue the tax invoice" and nothing else. A change goes through a
 * revised quotation or the owner.
 */
export default async function BuildInvoicePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ message?: string; error?: string }> }) {
  const staff = await requirePermission("viewInvoices");
  const role = staff.role_id as RoleId;
  const { id } = await params;
  const sp = await searchParams;
  const supabase = await createClient();
  const [card, settings] = await Promise.all([loadJobCard(supabase, id), getSettings()]);
  if (!card) notFound();
  const { job, vehicle, customer } = card;
  const admin = createAdminClient();
  const [draft, { data: existing }, { data: deposits }] = await Promise.all([
    buildInvoiceDraft(id, settings),
    admin.from("invoices").select(INVOICE_SELECT).eq("job_id", id).eq("is_active", true).order("issued_at", { ascending: false }),
    admin.from("payments").select(PAYMENT_SELECT).eq("job_id", id).eq("is_active", true).is("invoice_id", null),
  ]);
  const invoices = ((existing ?? []) as Record<string, unknown>[]).map(toInvoice);
  const taxInvoice = invoices.find((i) => i.kind === "tax_invoice" && i.status === "issued") ?? null;
  const proforma = invoices.find((i) => i.kind === "proforma" && i.status === "issued" && !i.converted_to) ?? null;
  const active = taxInvoice ?? proforma;
  const { data: activePays } = active ? await admin.from("payments").select(PAYMENT_SELECT).eq("invoice_id", active.id).eq("is_active", true) : { data: [] };
  const activeBalance = active ? invoiceBalance(active, ((activePays ?? []) as Record<string, unknown>[]).map(toPayment)) : null;
  const depositRows = ((deposits ?? []) as Record<string, unknown>[]).map(toPayment).filter((p) => p.status === "recorded");
  const depositTotal = depositRows.reduce((a, p) => a + p.amount_aed, 0);
  const canIssue = can(role, "issueInvoices") && !staff.viewingAs && job.is_open && !taxInvoice;
  const services = draft.lines.filter((l) => l.section !== "parts");
  const parts = draft.lines.filter((l) => l.section === "parts");

  return (
    <>
      <PageHeader title={`Invoice · ${formatPlate(vehicle)}`} subtitle={`${vehicleTitle(vehicle)} · ${job.job_number} · ${STATUS_LABELS[job.status]} · ${customer?.company_name ?? customer?.full_name ?? ""}`} actions={<><LinkButton href={`/jobs/${id}`} tone="secondary" size="lg">Job card</LinkButton><LinkButton href="/invoices" tone="secondary" size="lg">Invoices</LinkButton></>} />
      {sp.message ? <Notice tone="success">{sp.message}</Notice> : null}
      {sp.error ? <Notice tone="error">{sp.error}</Notice> : null}
      {taxInvoice ? <Notice tone="info">{taxInvoice.number} is issued for this job ({formatDateTime(taxInvoice.issued_at)}). Corrections are by credit note. <LinkButton href={`/invoices/${taxInvoice.id}`} tone="secondary" size="md">Open it</LinkButton></Notice> : null}
      {!active ? <Notice tone="info">No proforma yet. It is prepared by itself when the car is Ready, or with the button on the right. You can already see what it will say.</Notice> : null}
      {proforma && !taxInvoice ? <Notice tone="info">{proforma.number} is the proforma (not a tax invoice). Balance AED {m(activeBalance?.balance ?? 0)}. The tax invoice is generated by itself the moment the balance reaches zero.</Notice> : null}
      {draft.quotationNumbers.length === 0 && !job.inspection_fee_due ? <Notice tone="error">No approved quotation on this job and no inspection fee due. Nothing to invoice.</Notice> : null}

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <div className="xl:col-span-2 flex flex-col gap-4">
          <Card className="flex flex-col gap-2">
            <SectionLabel right={draft.quotationNumbers.length ? `a copy of ${draft.quotationNumbers.join(", ")}` : undefined}>Lines</SectionLabel>
            <p className="text-xs text-muted">Exactly what the customer approved: the same lines, discount and total. Nothing to choose or type here. A change needs a revised quotation or the owner.</p>
            {[{ title: "Services", ls: services }, { title: "Spare parts", ls: parts }].map(({ title, ls }) => (
              <div key={title} className="flex flex-col gap-1">
                <span className="text-xs font-bold uppercase tracking-[0.08em] text-muted">{title}</span>
                {ls.length === 0 ? <p className="text-sm text-muted">None</p> : null}
                <ul className="divide-y divide-line text-sm">
                  {ls.map((l, i) => (
                    <li key={i} className="py-1.5 flex flex-wrap items-center gap-3">
                      <span className="flex-1 min-w-48 font-semibold">{l.description}{l.part_number ? <span className="text-muted font-normal"> · {l.part_number}</span> : null}{l.section === "fees" ? <Badge tone="red">Fee</Badge> : null}{l.details && l.hours === null ? <span className="block text-xs text-muted font-normal">{l.details}</span> : null}</span>
                      <span className="text-muted w-20 text-right">{l.hours !== null ? `${l.hours.toFixed(1)} h` : `× ${l.quantity}`}</span>
                      <span className="w-24 text-right">{m(l.unit_price)}</span>
                      <span className="w-28 text-right font-semibold">{l.amount_aed === 0 ? "Complimentary" : `AED ${m(l.amount_aed)}`}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
            <dl className="grid grid-cols-[1fr_auto] gap-x-4 gap-y-1 text-sm border-t border-line pt-2">
              <dt className="text-muted">Gross amount</dt><dd className="text-right">AED {m(draft.totals.gross)}</dd>
              {draft.totals.discount ? <><dt className="font-bold">Discount on labour and services ({draft.totals.discountPercent}%), as quoted</dt><dd className="text-right font-bold">− AED {m(draft.totals.discount)}</dd></> : null}
              {draft.totals.warrantyCredit ? <><dt className="font-bold">Warranty repair, no charge</dt><dd className="text-right font-bold">− AED {m(draft.totals.warrantyCredit)}</dd></> : null}
              {draft.totals.rounding ? <><dt className="text-muted">Rounding, as quoted</dt><dd className="text-right">{draft.totals.rounding < 0 ? "− " : ""}AED {m(Math.abs(draft.totals.rounding))}</dd></> : null}
              <dt className="text-muted">Taxable amount</dt><dd className="text-right">AED {m(draft.totals.taxable)}</dd>
              <dt className="text-muted">VAT {draft.vatPercent}%</dt><dd className="text-right">AED {m(draft.totals.vat)}</dd>
              <dt className="text-lg font-extrabold">Total</dt><dd className="text-right text-lg font-extrabold">AED {m(draft.totals.total)}</dd>
              {depositTotal ? <><dt className="text-muted">Deposits received, applied on issue</dt><dd className="text-right">AED {m(depositTotal)}</dd></> : null}
            </dl>
            {draft.totals.warrantyCredit ? <p className="text-sm font-semibold">Warranty repair: the work and parts show at their normal value, then &quot;Warranty repair, no charge&quot; brings the total to zero.</p> : null}
          </Card>
        </div>

        <div className="flex flex-col gap-4">
          {canIssue && draft.lines.length ? (
            <Card className="flex flex-col gap-3 border-ink">
              <SectionLabel>{proforma ? "Tax invoice" : "Proforma"}</SectionLabel>
              {proforma ? <p className="text-sm">Generated by itself when {proforma.number} is paid in full.{role === "owner" ? " Only you can issue it earlier, with a reason; accounts are told." : " Only the owner can issue it earlier."}</p> : <p className="text-sm">Prepared by itself when the car is Ready. Prepare it now if the car is already here.</p>}
              <form action={issueInvoice.bind(null, id)} className="flex flex-col gap-2">
                {proforma && role === "owner" ? <Textarea name="reason" rows={2} required placeholder="Reason for issuing before full payment" /> : null}
                {proforma && role === "owner" ? <Button type="submit" size="lg" className="w-full">Issue the tax invoice now</Button> : null}
                {!proforma ? <Button type="submit" size="lg" className="w-full">Prepare the proforma</Button> : null}
              </form>
            </Card>
          ) : null}
          {invoices.length ? (
            <Card className="flex flex-col gap-1">
              <SectionLabel>Documents</SectionLabel>
              {invoices.map((i) => <p key={i.id} className="text-sm flex flex-wrap items-center gap-2"><LinkButton href={`/invoices/${i.id}`} tone="secondary" size="md">{i.number}</LinkButton><span className="text-xs text-muted">{i.kind === "tax_invoice" ? "Tax invoice" : i.kind === "proforma" ? (i.converted_to ? "Proforma, became the tax invoice" : "Proforma") : "Credit note"}</span></p>)}
            </Card>
          ) : null}
          {can(role, "recordPayments") && !staff.viewingAs && job.is_open && active && activeBalance && activeBalance.balance > 0 ? (
            <Card className="flex flex-col gap-3 border-ink">
              <SectionLabel right={`AED ${m(activeBalance.balance)} due`}>Payment against {active.number}</SectionLabel>
              <PaymentForm invoiceId={active.id} jobId={null} balance={activeBalance.balance} action={recordPayment} returnTo={`/jobs/${id}/invoice`} bankChargeCard={Number(settings.bank_charge_card_percent) || 0} bankChargeLink={Number(settings.bank_charge_link_percent) || 0} bankChargeCash={Number(settings.bank_charge_cash_percent) || 0} bankChargeCheque={Number(settings.bank_charge_cheque_percent) || 0} isOwner={role === "owner"} />
            </Card>
          ) : null}
          {can(role, "recordPayments") && !staff.viewingAs && !active && job.is_open ? (
            <Card className="flex flex-col gap-3">
              <SectionLabel right={draft.lines.length ? `AED ${m(Math.max(0, draft.totals.total - depositTotal))} to go` : undefined}>Deposit before the proforma</SectionLabel>
              {depositRows.map((p) => <p key={p.id} className="text-sm">{p.number} · AED {m(p.amount_aed)} by {p.method} · {formatDateTime(p.received_at)}</p>)}
              <PaymentForm invoiceId={null} jobId={id} balance={draft.lines.length ? Math.max(0, Math.round((draft.totals.total - depositTotal) * 100) / 100) : null} action={recordPayment} returnTo={`/jobs/${id}/invoice`} bankChargeCard={Number(settings.bank_charge_card_percent) || 0} bankChargeLink={Number(settings.bank_charge_link_percent) || 0} bankChargeCash={Number(settings.bank_charge_cash_percent) || 0} bankChargeCheque={Number(settings.bank_charge_cheque_percent) || 0} isOwner={role === "owner"} />
            </Card>
          ) : null}
        </div>
      </div>
    </>
  );
}
